### ISSUE TITLE
WebGL 1.0 Compatibility

### ISSUE THREAD

**Issue by Ninja-Koala** [beautypi/shadertoy-iOS-v2#14]
My iPhone 5 doesn't support WebGL 2.0, i would therefore be glad to see a compatibility mode to support WebGL 1.0 shaders, like the website does. At the moment i just get the error message "Failed to create ES context".

**Comment by reindernijhoff** [comment]
Hi,

Yes you're right. I had to switch from OpenGL ES 2.0 to OpenGL ES 3.0. That's because OpenGL ES 3.0 has (almost) the same syntax as WebGL 2 which is the new WebGL version used on Shadertoy.

I will have a look if it's possible to make an OpenGL ES 2.0 fallback (and automatically rewrite the WebGL 2 shaders to a WebGL 1 syntax).
